---
base_data_dir: "./data"

recipe_pages_info:
  recipe_root_url: https://www.tarladalal.com
  columns_to_use: ["recipe_name", "ingredients", "recipe", "tags", "times", "servings"]

  gj:
    list_page_url: recipes-for-veg-recipes-gujarati-24?pageindex={0}
    last_list_page_num: 38
  mh:
    list_page_url: recipes-for-veg-recipes-maharashtrian-52?pageindex={0}
    last_list_page_num: 21

embedding_model: 'text-embedding-3-large' #"Alibaba-NLP/gte-large-en-v1.5" # Chosen from https://huggingface.co/spaces/mteb/leaderboard

vector_store:
  dir: "./ai/vectors"
  index_name: "recipe_ai"

auth:
  allowed_users: ['shalin', 'nisha', 'sakshar', 'manali', 'sagar', 'grishma']
  access_token_expires_minutes: 1440
  algorithm: 'HS256'
